### ISSUE TITLE
Click on Barcode Scanner Crashes App

### ISSUE THREAD

**Issue by wreardan** [ckumar1/smart-fridge-android#20]
I clicked on the barcode scanner link to scan a barcode which causes the app to crash.

I can then no longer access the 'Manual' or 'Barcode' links on the Recipe page even after rebooting the phone, wiping the application's data, and re-installing the application.
EDIT: this was a user-error -> I missed the Add button on the second go through, may want to make it larger.

This issue was caused by not having zxing installed.  I recommend checking for that condition then bringing the user to Google Play where they can download the required barcode scanner app.

**Comment by corypgr** [comment]
It now asks the user if they want to download the zxing app if they do not have a barcode scanner app 7c9c97f5e598aa398618552f6f4c00b4253697dc
