### ISSUE TITLE
Format in adding and viewing user recipe is very odd

### ISSUE THREAD

**Issue by katamaritaco** [ckumar1/smart-fridge-android#25]
I'm using a nexus 7, which isn't a phone, but it seems the way the views were embedded and made in the user recipe activities is just bizarre with weird formatting issues happening everywhere.
![screenshot_2014-05-02-12-43-36](https://cloud.githubusercontent.com/assets/1427530/2866245/5b889eb8-d226-11e3-9e57-16e5c7e258ba.png)

![screenshot_2014-05-02-13-20-19](https://cloud.githubusercontent.com/assets/1427530/2866260/8125ec02-d226-11e3-8838-38123ce24720.png)

**Comment by katamaritaco** [comment]
The above pictures are food type. This is a recipe type. 
![screenshot_2014-05-02-13-29-32](https://cloud.githubusercontent.com/assets/1427530/2866360/dddba9f4-d227-11e3-9b1e-416f799a7495.png)

**Comment by katamaritaco** [comment]
Severity: Mild (But easy to fix)

**Comment by corypgr** [comment]
These have been changed in 39164143210cc507e62828b835fffba742be61b1 and cd3b9060e65bb6e35bdbeb0f12fd272c91a870b0
