### ISSUE TITLE
Add button is very small

### ISSUE THREAD

**Issue by jaltekruse** [ckumar1/smart-fridge-android#29]
Phone screen space is limited, but the button show up very small on my phone, screenshot it in the 4th image of the gallery. The food, recipes, settings buttons are appropriate size but the add button is a bit hard to hit.

http://imgur.com/a/XBuuQ

**Comment by jaltekruse** [comment]
Severity: minor

**Comment by corypgr** [comment]
I've increased the button sizes for both add and logout. f81c53b91b2f2c6716189d17ffc521efd5ecbc15
